// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzvZQeS8q7fMOX6MCAd2HvPa6c2BAho7c',
    appId: '1:770412894457:web:995aa48b54b8deefb5aa28',
    messagingSenderId: '770412894457',
    projectId: 'chatwith-23601',
    authDomain: 'chatwith-23601.firebaseapp.com',
    storageBucket: 'chatwith-23601.appspot.com',
    measurementId: 'G-PDKCN9K2BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYi08mJetBn5z4gSAAFB27tYq0Hyoozk',
    appId: '1:770412894457:android:f7f08c9ec229ae49b5aa28',
    messagingSenderId: '770412894457',
    projectId: 'chatwith-23601',
    storageBucket: 'chatwith-23601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzc8K-wuKrGJk4SEkAMIV80VxDwS8sRc',
    appId: '1:770412894457:ios:03589a736b591083b5aa28',
    messagingSenderId: '770412894457',
    projectId: 'chatwith-23601',
    storageBucket: 'chatwith-23601.appspot.com',
    iosClientId: '770412894457-2an96a1lvl02o7jlepdmeju0l22hf1k1.apps.googleusercontent.com',
    iosBundleId: 'com.Avinash56.chatwith',
  );
}
